### ISSUE TITLE
疑问。

### ISSUE THREAD

**Issue by mutousay** [chenjinxuan/chess#1]
每个服务下的vendor下的代码，不是有很多重复的直接放到最外层不行吗？  
比如vendor/chess/commom 中的services.go 这个应该都是一样的吧？ 或者直接把所有服务的vendor/chess/commom这个目录整合到一起放到最外层，这样做会有什么问题吗？

**Comment by chenjinxuan** [comment]
你可以理解为每个服务都是独立的,所以每个服务都需要单独的vendor依赖包,,docker 部署就是这样的,,如果不用docker,那么目录结构可以随意,vendor也不可以不用

**Comment by mutousay** [comment]
ok
